export const storeProducts = [
  {
    id: 1,
    title: "IV CS1",
    img: "/img/product-1.png",
    price: 4500,
    company: "Zifam",
    info:
      "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Zifam Levofloxacin",
    img: "/img/product-2.png",
    price: 4500,
    company: "Zifam",
    info:
      "Levofloxacin Tablets are indicated for the treatment of adults with bacterial infection caused by susceptible of the designated microorganisms in the infection listed below. Upper and lower Respiratory Tract Infections Uncomplicated skin and skin structure infection, Complicated skin and skin structure infections(mild to moderate), excluding burns Urinary Tract infections",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "IV Amikacin zifam",
    img: "/img/product-3.png",
    price: 4500,
    company: "Zifam",
    info:
      "Serious Bacterial Infections Intra-abdominal Infections Meningitis and Other CNS Infections Mycobacterial Infections Other Mycobacterial Infections Nocardia Infections Empiric Therapy in Febrile Neutropenic Patient",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "IV Multivit zifam",
    img: "/img/product-4.png",
    price: 4500,
    company: "Zifam",
    info:
      "Aids, assists or helps in the maintenance or improvement of general well-being.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "IV Ofloxacin",
    img: "/img/IVOfloxacin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Ofloxacin is a quinolone antimicrobial agent. The mechanism of action of ofloxacin and other fluoroquinolone antimicrobials involves inhibition of bacterial topoisomerase IV and DNA gyrase (both of which are type II topoisomerases) enzymes required for DNA replication, transcription, repair and recombination",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "IV Augmentin",
    img: "/img/IVAugmentin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Search Results Featured snippet from the web Augmentin is for intravenous use. Augmentin may be administered either by slow intravenous injection over a period of 3 to 4 min directly into a vein or via a drip tube or by infusion over 30 to 40 min. Augmentin is not suitable for intramuscular administration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Oral Amoxicillin",
    img: "/img/OralAmoxicillin.png",
    price: 4500,
    company: "Zifam",
    info:
      "Amoxicillin is used to treat bacterial infections in many different parts of the body. It is also used with other medicines (e.g., clarithromycin, lansoprazole) to treat H. pylori infection and duodenal ulcers.Amoxicillin belongs to the group of medicines known as penicillin antibiotics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Oral Multivit",
    img: "/img/Oralmultivit.png",
    price: 4500,
    company: "Zifam",
    info:
      "BetterYou MultiVit Oral Spray is an expert blend of 14 essential vitamins and minerals, that work together to support your body¿s immune system.  The robust multi-nutrient formulation contains the full spectrum of B vitamins, including folate, combined with vitamins A, C, D, K, selenium and iodine.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "FLUMOX 500mg Vial",
    img: "/img/OralFlumox1.png",
    price: 5000,
    company: "Zifam",
    info:
      "Amoxicillin is a semisynthetic antibiotic, an analog of ampicillin, with a broad spectrum of bactericidal activity against many gram-positive and gram-negative microorganisms. Chemically it is ohydrate for oral use and as sodium salt for parenteral use.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Oral paracetamol",
    img: "/img/OralParacetamol.png",
    price: 5000,
    company: "Zifam",
    info:
      "CLOFEN PLUS is used in the Management of osteoarthritis, rheumatoid arthritis and ankylosing spondylitis. NSAIDs are used for the relief of mild to moderate pain, minor febrile conditions and for acute and chronic inflammatory disorders such as osteoarthritis, rheumatoid arthritis, juvenile chronic arthritis and ankylosing spondylitis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Oral diclofenac",
    img: "/img/OralDiclofenac.png",
    price: 5000,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Oral pantocid",
    img: "/img/OralPantocid.png",
    price: 4500,
    company: "Zifam",
    info:
      "Pantoprazole 40 is indicated for the short-term treatment of duodenal ulcer, gastric ulcer and reflux oesophagitis. If the duodenal ulcer has been demonstrated to be associated with Helicobacter pylori infection. Pantoprazole 40used in combination with appropriate antibiotic may be useful.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "IV CS1",
  img: "/img/product-1.png",
  price: 4500,
  company: "Zifam",
  info:
    "Zifam CS1/CS2 is indicated for the treatment of the following infections when caused by susceptible organisms Respiratory Tract Infections (Upper and Lower) Urinary Tract infections(Upper and Lower) Peritonitis, Cholecystitis, Cholangitis, and Other Intra- Abdominal Infections Septicemia Meningtis Skin and Soft Tissue Infections Bone and Joint Infections Pelvic inflammatory Disease, Endometritis, Gonorrhea, and Other Infections of the Genital Tract",
  inCart: false,
  count: 0,
  total: 0,
};
// Next Page about Oral
